- type: job
  id: MedicalIntern
  name: job-name-intern
  description: job-description-intern
  playTimeTracker: JobMedicalIntern
#  requirements: # starcup: remove intern lockout
#    - !type:DepartmentTimeRequirement
#      department: Medical
#      time: 54000 # 15 hrs
#      inverted: true # stop playing intern if you're good at med!
  startingGear: MedicalInternGear
  icon: "JobIconMedicalIntern"
  supervisors: job-supervisors-medicine
  canBeAntag: false
  access:
  - Medical
  - Maintenance

- type: startingGear
  id: MedicalInternGear
  equipment:
#    shoes: ClothingShoesColorWhite # starcup: replaced with loadout
#    id: MedicalInternPDA # DeltaV: different PDAs in loadouts
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    pocket2: BookMedicalReferenceBook
  #storage:
    #back:
    #- Stuff
