- type: job
  id: Roboticist
  name: job-name-roboticist
  description: job-description-roboticist
  playTimeTracker: JobRoboticist
  antagAdvantage: 6 # The shadow factory + scientist advantage
  requirements:
  - !type:DepartmentTimeRequirement
    department: Science # starcup: science, was epistemics
    time: 7200 # starcup: 2 hours, was 4
  - !type:DepartmentTimeRequirement # starcup: make roboticist hybrid role.
    department: Engineering
    time: 7200 # 2 hours
  # begin starcup
  #- !type:OverallPlaytimeRequirement
  #  time: 43200 # 12 hours
  # end starcup
  startingGear: RoboticistGear
  icon: JobIconRoboticist
  supervisors: job-supervisors-rd
  access:
  - Research
  - Robotics
  - Maintenance
  - Engineering # starcup: make roboticist a hybrid role. can be changed to extendedAccess if needed

- type: startingGear
  id: RoboticistGear
  equipment:
    ears: ClothingHeadsetRobotics
    belt: ClothingBeltUtilityEngineering # starcup: make roboticist hybrid role
