- type: job
  id: Bartender
  name: job-name-bartender
  description: job-description-bartender
  playTimeTracker: JobBartender
# begin starcup
#  requirements:
#    - !type:DepartmentTimeRequirement
#      department: Civilian
#      time: 1800
# end starcup
  startingGear: BartenderGear
  icon: "JobIconBartender"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Bar
  extendedAccess:
  - Kitchen
  - Hydroponics

- type: startingGear
  id: BartenderGear
  equipment:
#    shoes: ClothingShoesColorBlack # starcup: moved to loadouts
    id: BartenderPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff
