- type: job
  id: Chef
  name: job-name-chef
  description: job-description-chef
  playTimeTracker: JobChef
# begin starcup
#  requirements:
#    - !type:DepartmentTimeRequirement
#      department: Civilian
#      time: 1800
# end starcup
  startingGear: ChefGear
  icon: "JobIconChef"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Kitchen
  extendedAccess:
  - Hydroponics
  - Bar

- type: startingGear
  id: ChefGear
  equipment:
#    shoes: ClothingShoesColorBlack # starcup: replaced with loadout
#    id: ChefPDA # DeltaV: different PDAs in loadouts
    ears: ClothingHeadsetService
    belt: ClothingBeltChefFilled
  #storage:
    #back:
    #- Stuff
